const features = [
  {
    title: "Conversational intake",
    body: "The household explains the problem in their own words. The agent asks at most two clarifying questions."
  },
  {
    title: "Deterministic safety triage",
    body: "Gas, smoke, water near electrics and vulnerable occupants are handled by rules, never by the model."
  },
  {
    title: "Executable plan",
    body: "Every plan has urgency, owners, deadlines, sources and explicit confirmation before any external action."
  },
  {
    title: "NVIDIA model on Nebius",
    body: "Nemotron extracts constraints and drafts the structured plan; Tavily adds current public sources."
  }
];

export default function HomePage() {
  return (
    <div className="space-y-10">
      <section className="card p-8">
        <p className="text-xs uppercase tracking-widest text-sky-400">Household operations agent</p>
        <h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-tight">
          &ldquo;The boiler is making a noise and we have guests on Saturday&rdquo; becomes an executable plan.
        </h1>
        <p className="mt-4 max-w-2xl text-slate-300">
          HomeOps AI coordinates household repairs: it triages risk, builds a plan with owners and deadlines, researches current options and
          tracks the actions until they are done — across conversations.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a className="rounded-lg bg-sky-500 px-5 py-2.5 font-medium text-slate-950 hover:bg-sky-400" href="/alexa">
            Start the Alexa+ demo
          </a>
          <a className="rounded-lg border border-slate-600 px-5 py-2.5 font-medium hover:border-slate-400" href="/nebius">
            See the agent trace
          </a>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        {features.map((feature) => (
          <article key={feature.title} className="card p-6">
            <h2 className="text-lg font-medium">{feature.title}</h2>
            <p className="mt-2 text-sm text-slate-300">{feature.body}</p>
          </article>
        ))}
      </section>

      <section className="card p-6 text-sm text-slate-300">
        <h2 className="text-base font-medium text-slate-100">Demo data</h2>
        <p className="mt-2">
          Everything in the demo is synthetic: a fictional household in Bristol, no real people, addresses or phone numbers. Emergency
          guidance uses UK public numbers (999 and 0800 111 999) and is written by humans, not generated by a model.
        </p>
      </section>
    </div>
  );
}
