/**
 * Deterministic safety copy, written by humans and never generated by a model.
 * UK phone numbers: 999 for emergencies, 0800 111 999 for the National Gas
 * Emergency Service (England, Scotland and Wales).
 */

export const EMERGENCY_NUMBER_UK = "999";
export const GAS_EMERGENCY_NUMBER_UK = "0800 111 999";

export const GAS_GUIDANCE = [
  `Smell of gas: do not switch anything on or off, do not use a flame or a phone inside, open doors and windows, leave the property and call the National Gas Emergency Service on ${GAS_EMERGENCY_NUMBER_UK}.`
];

export const FIRE_GUIDANCE = [
  `Smoke, fire or burning: get everyone out, stay out and call ${EMERGENCY_NUMBER_UK}. Never pour water on an electrical fire.`
];

export const ELECTRICAL_GUIDANCE = [
  `Water near sockets or electrics: do not touch the wet area or any electrical item; switch the power off only from a dry, safe position and call ${EMERGENCY_NUMBER_UK} if anyone is at risk of electric shock.`
];

export const CARBON_MONOXIDE_GUIDANCE = [
  `Carbon monoxide is invisible and can be fatal: open windows, leave the property and call the National Gas Emergency Service on ${GAS_EMERGENCY_NUMBER_UK}; call ${EMERGENCY_NUMBER_UK} if anyone feels unwell.`
];

export const HEAT_LOSS_GUIDANCE = [
  "No heating or hot water: keep at least one room warm with a safe temporary heater, check on anyone vulnerable, and book a Gas Safe registered engineer for boiler work.",
  "Do not open the boiler casing or attempt a repair yourself; gas appliances must be worked on by a Gas Safe registered engineer."
];

export const BOILER_NOISE_GUIDANCE = [
  "Boiler noise without gas, smoke or a visible leak is usually not an emergency, but it should be inspected before it becomes one.",
  "Do not open the boiler casing; only a Gas Safe registered engineer should work on a gas appliance."
];

export const COORDINATOR_DISCLAIMER =
  "HomeOps AI is a household coordination tool. It does not provide professional diagnosis, gas, electrical or legal advice.";
